# Generated by Django 3.2.11 on 2023-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0002_auto_20230208_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details3_1_1',
            name='Year_of_Award',
            field=models.DateTimeField(default=0),
        ),
    ]
