# Generated by Django 3.2.11 on 2023-02-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0004_details3_2_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details3_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_paper', models.CharField(max_length=200)),
                ('Name_of_the_authors', models.CharField(max_length=200)),
                ('Department_of_the_teacher', models.CharField(choices=[('Automobile Engineering', 'Automobile Engineering'), ('Basic Science and Humanities', 'Basic Science and Humanities'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=60)),
                ('Name_of_journal', models.CharField(max_length=200)),
                ('Year_of_publication', models.DateField(default=0)),
                ('ISSN_number', models.IntegerField(default=0)),
                ('Link_to_website_of_the_Journal', models.URLField(default=None)),
                ('Link_to_article_paper_abstract_of_the_article', models.URLField(default=None)),
                ('Is_it_listed_in_UGC_Care_list', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='details3_2_2',
            name='Date_From',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='details3_2_2',
            name='Date_To',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='details3_2_2',
            name='Year',
            field=models.DateField(default=None),
        ),
    ]
