# Generated by Django 3.2.11 on 2023-02-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0005_auto_20230209_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details3_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_teacher', models.CharField(max_length=50)),
                ('Title_of_the_book_chapters_published', models.CharField(max_length=200)),
                ('Title_of_the_paper', models.CharField(max_length=100)),
                ('Title_of_the_proceedings_of_the_conference', models.CharField(max_length=200)),
                ('Name_of_the_conference', models.CharField(max_length=200)),
                ('national_international', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=50)),
                ('Year_of_publication', models.DateField(default=None)),
                ('ISBN_number_of_the_proceeding', models.IntegerField(default=0)),
                ('Affiliating_Institute_at_the_time_of_publication', models.CharField(max_length=200)),
                ('Name_of_the_publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
