# Generated by Django 3.2.11 on 2023-02-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0006_details3_3_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details3_4_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_activity', models.CharField(max_length=200)),
                ('Organising_unit_agency_collaborating_agency', models.CharField(max_length=200)),
                ('Name_of_the_scheme', models.CharField(max_length=60)),
                ('Year_of_the_activity', models.DateField(default=None)),
            ],
        ),
    ]
