# Generated by Django 3.2.11 on 2023-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0008_details3_5_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='details3_1_1',
            name='Uploaded_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='details3_2_2',
            name='Uploaded_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='details3_3_1',
            name='Uploaded_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='details3_3_2',
            name='Uploaded_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='details3_4_3',
            name='Uploaded_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='details3_5_1',
            name='Uploaded_by',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
