# Generated by Django 3.2.11 on 2023-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0011_auto_20230217_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details3_1_1',
            name='Year_of_Award',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='details3_2_2',
            name='Date_From',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='details3_2_2',
            name='Date_To',
            field=models.DateField(default=None),
        ),
    ]
