# Generated by Django 3.2.11 on 2023-03-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0012_auto_20230222_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details3_3_2',
            old_name='Year_of_publication',
            new_name='Year_of_publications',
        ),
    ]
