# Generated by Django 3.2.11 on 2023-03-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0014_alter_details3_1_1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details3_1_1',
            options={},
        ),
    ]
