# Generated by Django 3.2.11 on 2023-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0015_alter_details3_1_1_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='details3_2_2',
            name='radiobutton322',
            field=models.CharField(choices=[('Research Methodology', 'Research Methodology'), ('Intellectual Property Rights (IPR)', 'Intellectual Property Rights (IPR)'), ('Entrepreneurship', 'Entrepreneurship')], default=None, max_length=50),
        ),
    ]
