# Generated by Django 3.2.11 on 2023-03-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0017_alter_details3_2_2_radiobutton322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details3_2_2',
            name='radiobutton322',
            field=models.CharField(choices=[('Research Methodology', 'Research Methodology'), ('Intellectual Property Rights (IPR)', 'Intellectual Property Rights (IPR)'), ('Entrepreneurship', 'Entrepreneurship')], default=None, max_length=50),
        ),
    ]
