# Generated by Django 3.2.11 on 2023-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0018_alter_details3_2_2_radiobutton322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Citations', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('i10_index', models.IntegerField(default=0)),
                ('profile_link', models.CharField(max_length=200)),
            ],
        ),
    ]
