# Generated by Django 3.2.11 on 2023-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0019_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='Cemail',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='citations',
            name='Department',
            field=models.CharField(choices=[('Automobile Engineering', 'Automobile Engineering'), ('Basic Science and Humanities', 'Basic Science and Humanities'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='citations',
            name='Name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='citations',
            name='year',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default=None, max_length=60),
        ),
    ]
