# Generated by Django 3.2.11 on 2023-02-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdetails',
            old_name='Confirm_password',
            new_name='RConfirm_password',
        ),
        migrations.RenameField(
            model_name='rdetails',
            old_name='Email',
            new_name='REmail',
        ),
        migrations.RenameField(
            model_name='rdetails',
            old_name='Name',
            new_name='RName',
        ),
        migrations.RenameField(
            model_name='rdetails',
            old_name='Password',
            new_name='RPassword',
        ),
    ]
