# Generated by Django 3.2.11 on 2023-02-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20230206_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdetails',
            old_name='RPassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='rdetails',
            old_name='REmail',
            new_name='username',
        ),
    ]
