# Generated by Django 3.2.11 on 2023-02-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_auto_20230206_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdetails',
            old_name='username',
            new_name='REmail',
        ),
        migrations.RenameField(
            model_name='rdetails',
            old_name='password',
            new_name='RPassword',
        ),
    ]
