# Generated by Django 3.2.11 on 2023-02-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_useraccounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccounts',
        ),
    ]
