# Generated by Django 3.2.11 on 2023-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_delete_useraccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdetails',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
