# Generated by Django 3.2.11 on 2023-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_rdetails_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdetails',
            name='RConfirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rdetails',
            name='RPassword',
            field=models.CharField(max_length=100),
        ),
    ]
